---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes

- name: "install dependencies"
  become: yes
  apt: 
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "get application code"
  git:
    repo: https://github.com/ccaloian/udapeople.git
    dest: /home/ubuntu/udapeople

# - name: "execute shell commands"
#   shell: |
#     echo "Hello World"

- name: "executing node"
  shell: |
    cd /home/ubuntu/udapeople/backend
    pm2 start npm -- run "start:dev"