---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm", "tar"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Make backend dir"
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy dist files"
  become: true
  copy:
    src: backend_artifact.tar.gz
    dest: /home/ubuntu/backend/backend_artifact.tar.gz

- name: Unpack dist files and start the app
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -xzf backend_artifact.tar.gz
    rm backend_artifact.tar.gz

- name: Build backend and prestart:prod
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm run prestart:prod

- name: Stop old backend process
  become: true
  shell: |
    pm2 stop backend
    pm2 delete backend

- name: Start the app backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- run start
    pm2 ls
